### ISSUE TITLE
追番界面无法正常显示，提示token有误，服务器时区不统一

### ISSUE THREAD

**Issue by Xunflash** [bakaomg/castle-Typecho-Theme#17]
![屏幕截图 2020-09-26 041709](https://user-images.githubusercontent.com/71567536/94312495-95742d00-ffaf-11ea-9caa-cfe182b6a7a9.png)
如图，博客使用的是uhttpd+php+sqlite3环境

**Comment by bakaomg** [comment]
注：已在群内解决，故关闭此 issue
