### ISSUE TITLE
追番页面不能加载

### ISSUE THREAD

**Issue by a641764137** [bakaomg/castle-Typecho-Theme#18]
追番页面不能加载，一直转圈圈，已按照主题文档的方式来设置但问题依旧。

**Comment by kengwang** [comment]
Hi,感谢您提交此Issue,为了更好的提供帮助,您可以提供网址,错误报告等信息来使我们更加快速的定位错误

**Comment by a641764137** [comment]
我的blog地址:https://coolming.tk/
页面tmp和追番页面为我设置的追番页面

**Comment by kengwang** [comment]
![图片](https://user-images.githubusercontent.com/30862240/101987098-fcf76a00-3ccc-11eb-87c6-fd9ea751fd97.png)
可见该请求已经传输到服务器,但是服务器未返回任何的番剧数据

**Comment by a641764137** [comment]
请问，是我服务器但问题吗？

**Comment by kengwang** [comment]
等下,我看看代码,因为代码是OMG大佬写的

**Comment by a641764137** [comment]
我设置的是bilibili的，不过这里显示为bangumi，是不是有bug呢？
以下是nginx的错误信息
`2020/12/12 22:27:49 [error] 1205#1205: *1452 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: data in /usr/share/nginx/html/usr/plugins/Castle/libs/bangumi.php on line 75PHP message: PHP Notice:  Trying to access array offset on value of type null in /usr/share/nginx/html/usr/plugins/Castle/libs/bangumi.php on line 75" while reading response header from upstream, client: 127.0.0.1, server: coolming.tk, request: "GET /index.php/action/castle?type=bangumi&auth=8296e330095a207dfd7a663a10af4a95 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "coolming.tk", referrer: "https://coolming.tk/index.php/30.html"
2020/12/12 22:28:15 [error] 1205#1205: *1452 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 127.0.0.1, server: coolming.tk, request: "GET /favicon.ico HTTP/1.1", host: "coolming.tk", referrer: "https://coolming.tk/index.php/feed/"
2020/12/12 22:28:52 [error] 1205#1205: *1486 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: result in /usr/share/nginx/html/var/Widget/Ajax.php on line 71" while reading response header from upstream, client: 127.0.0.1, server: coolming.tk, request: "GET /index.php/action/ajax?do=checkVersion HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "coolming.tk", referrer: "https://coolming.tk/admin/"
2020/12/12 22:28:58 [error] 1205#1205: *1452 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: result in /usr/share/nginx/html/var/Widget/Ajax.php on line 71" while reading response header from upstream, client: 127.0.0.1, server: coolming.tk, request: "GET /index.php/action/ajax?do=checkVersion HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "coolming.tk", referrer: "https://coolming.tk/admin/index.php"
2020/12/12 22:41:45 [error] 8268#8268: *4 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: result in /usr/share/nginx/html/var/Widget/Ajax.php on line 71" while reading response header from upstream, client: 127.0.0.1, server: coolming.tk, request: "GET /index.php/action/ajax?do=checkVersion HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "coolming.tk", referrer: "https://coolming.tk/admin/"`

**Comment by kengwang** [comment]
建议检查一下是否正确填写SESSDATA和uid等信息,等下我去叫OMG大佬

**Comment by a641764137** [comment]
已确认uid和SESSDAT没问题，blog后台也已设置为bilibili追番，不过我看见日志的type为bangumi的，不清楚是不是我配置有问题。

**Comment by kengwang** [comment]
![图片](https://user-images.githubusercontent.com/30862240/101987289-2664c580-3cce-11eb-87f7-e687a92a6844.png)
Type为Bilibili,

可能需要输出一下某些信息,方便修改服务器上的源代码吗?
> PS: 主题交流群: 1033117896
> Kengwang の QQ : 1136772134

**Comment by kengwang** [comment]
![图片](https://user-images.githubusercontent.com/30862240/101987345-80fe2180-3cce-11eb-8418-814575405d56.png)
可以`插件\libs\bangumi.php`在72行加入
>   echo $data;
查看下详细的错误信息

**Comment by a641764137** [comment]
已在72行加入，请问要怎么查看错误信息呢？

**Comment by kengwang** [comment]
> 
> 
> 已在72行加入，请问要怎么查看错误信息呢？

方便的话可以加私人QQ: 1136772134

**Comment by CberYellowstone** [comment]
> > 已在72行加入，请问要怎么查看错误信息呢？
> 
> 方便的话可以加私人QQ: 1136772134

为什么不去群里bb呢(

**Comment by a641764137** [comment]
已发送请求

**Comment by kengwang** [comment]
> PS: 主题交流群: 1033117896
> Kengwang の QQ : 1136772134

我发了的

**Comment by CberYellowstone** [comment]
> > PS: 主题交流群: 1033117896
> > Kengwang の QQ : 1136772134
> 
> 我发了的

我成功复现了此问题,也是data体为空

**Comment by kengwang** [comment]
![图片](https://user-images.githubusercontent.com/30862240/101987648-76448c00-3cd0-11eb-87dc-b8a5798a41e2.png)
![图片](https://user-images.githubusercontent.com/30862240/101987652-7c3a6d00-3cd0-11eb-84d5-a15b01e12ba1.png)
![图片](https://user-images.githubusercontent.com/30862240/101987645-6d53ba80-3cd0-11eb-8b9e-890fe7ccc168.png)

**Comment by kengwang** [comment]
Issue Fixed

**Comment by a641764137** [comment]
主题附带的插件有点问题，去 https://github.com/bakaomg/Castle-Plugin 下载master分支的插件后替换掉原有的Castle插件，问题解决！
