### ISSUE TITLE
Please make use of "branch"

### ISSUE THREAD

**Issue by xtlsoft** [bakaomg/castle-Typecho-Theme#2]
Git has a functionality called "branch".

You don't need to delete all files at all. You just need to open a new branch with `git branch NEW_BRANCH_NAME` and `git checkout NEW_BRANCH_NAME`.

By the way, here's a guy http://ktv.gjwa.top/ who abuses your theme and deletes the copyright links.

He also sent 
![image](https://user-images.githubusercontent.com/16159830/73133322-0a2e4a80-4062-11ea-871e-4bcde96c8489.png)
in a group I added for fun.

**Comment by bakaomg** [comment]
tanks🙃
