### ISSUE TITLE
Ver 0.9.6 二维码显示不正确

### ISSUE THREAD

**Issue by CberYellowstone** [bakaomg/castle-Typecho-Theme#20]
现象：跨设备阅读二维码不显示，如下图
---
![image](https://user-images.githubusercontent.com/37031767/115133377-4a4c6500-a03a-11eb-9712-880cc383744f.png)
---
# 已在官方DEMO中复现

## @bakaomg 发新版也不测测新功能，出来挨打

**Comment by kengwang** [comment]
经过我的简单排查,deviceQR方法内部并无错误,但是并未被调用

**Comment by kengwang** [comment]
Chrome上此问题复现,FireFox Developer Edition 上无法复现 (只能用Chrome的垃圾调试器来调试一下了)

**Comment by CberYellowstone** [comment]
> Chrome 上此问题复现，FireFox Developer Edition 上无法复现 (只能用 Chrome 的垃圾调试器来调试一下了)

确实，Firefox 上没这问题，看看到底是哪里导致 Chrome 上面出问题了

**Comment by CberYellowstone** [comment]
> Chrome 上此问题复现，FireFox Developer Edition 上无法复现 (只能用 Chrome 的垃圾调试器来调试一下了)

![image](https://user-images.githubusercontent.com/37031767/115133854-e0ce5580-a03d-11eb-9cb7-fd52ea610057.png)
---
手动执行这段js能正常显示

**Comment by kengwang** [comment]
Chrome的调试器有点渣,不好在执行的地方下断点,我这边尝试本地搞一个Typecho试试

**Comment by CberYellowstone** [comment]
> Chrome 的调试器有点渣，不好在执行的地方下断点，我这边尝试本地搞一个 Typecho 试试

初步猜想是这个判断不兼容 Chrome
(乱猜的，没验证


---
![image](https://user-images.githubusercontent.com/37031767/115133957-bf219e00-a03e-11eb-8c06-af4caf7c9e4c.png)

**Comment by kengwang** [comment]
不兼容的话应该会有控制台报错的,但是控制台却没针对这个的报错. 可能是某个if条件没有走通

**Comment by kengwang** [comment]
经过调试,发现从始至终Chrome并未调用那个function

**Comment by kengwang** [comment]
是Chrome的异常抛出在highlight函数这里,然后导致在他后面的deviceQR未能执行
![image](https://user-images.githubusercontent.com/30862240/115134117-0b211280-a040-11eb-9802-c29ef00c13f7.png)

**Comment by kengwang** [comment]
![image](https://user-images.githubusercontent.com/30862240/115134134-2ab83b00-a040-11eb-9762-090abb7edf48.png)
将highlight函数进行try...catch并忽略异常后,二维码成功显示
相关代码如下
```js
// 此方法仅为测试错误使用,请不要再生产环境使用
highLight: function() {
      try {
         $$('code[class^="lang"]:not(pre code)').each((function(key, item) {
            let child = item
              , parent = document.createElement("pre");
            child.parentNode.replaceChild(parent, child),
            parent.appendChild(child)
        }
        )),
        $$("pre code").each((function(key, item) {
            !1 === item.classList.contains("hljs") && $$(this).html("<ol><li>" + $$(this).html().replace(/\n/g, "\n</li><li>") + "\n</li></ol>")
        }
        )),
        $$(document).ready((function() {
            $$("pre code").each((function(key, item) {
                !1 === item.classList.contains("hljs") && hljs.highlightBlock(item)
            }
            ))
        }
        ))
      } catch (error) {
         //ignore
      }
       
   },
```

**Comment by kengwang** [comment]
后话: 根治这个问题的方法是修复highLight函数的问题,上面那个仅是加了个try catch来暴力忽略错误
好像是Chrome的QuerySelector不支持`:not`语法而FireFox支持此语法
建议 @bakaomg 在之后换一下这个QuerySelector

**Comment by bakaomg** [comment]
emmm 我在本地测试是完全没问题的，奇怪了

**Comment by bakaomg** [comment]
@Kengwang 
![image](https://user-images.githubusercontent.com/40896676/115134382-255bf000-a042-11eb-9ee3-72912383bd5d.png)
其实是支持的（

**Comment by kengwang** [comment]
![image](https://user-images.githubusercontent.com/30862240/115134403-4fadad80-a042-11eb-9ff5-050a68ea8afb.png)
是新功能吗?我用的Cent Browser (`Chrome 86.0.4240.198`)

**Comment by bakaomg** [comment]
这边测试环境是 `Chrome 89.0.4389.114`

**Comment by kengwang** [comment]
Google Chrome 90.0.4430.72 不复现 QAQ
这是要让我回归Chrome的节奏吗? QAQ 我挺舍不得 Cent Browser的

**Comment by bakaomg** [comment]
而且我发现一个问题，生产环境和开发环境差别很大，比如评论区代码高亮的换行没了
很奇怪...

**Comment by CberYellowstone** [comment]
> ![image](https://user-images.githubusercontent.com/30862240/115134403-4fadad80-a042-11eb-9ff5-050a68ea8afb.png)
> 是新功能吗？我用的 Cent Browser (`Chrome 86.0.4240.198`)

我也是 Cent Browser (`Chrome 86.0.4240.198`) XD

**Comment by CberYellowstone** [comment]
> @kengwang
> ![image](https://user-images.githubusercontent.com/40896676/115134382-255bf000-a042-11eb-9ee3-72912383bd5d.png)
> 其实是支持的（

![image](https://user-images.githubusercontent.com/37031767/115134771-ba141d00-a045-11eb-9f34-173b3c443c99.png)
---

Chrome 要 88 以上
~~建议马上改个适用性强一点的方法~~

**Comment by bakaomg** [comment]
emmm 其实历史版本中有多处使用了 `:not` 选择器... 好像也没出现过很严重的问题
我尝试用其他方法实现（

**Comment by CberYellowstone** [comment]
> emmm 其实历史版本中有多处使用了 `:not` 选择器... 好像也没出现过很严重的问题
> 我尝试用其他方法实现（

`:not`有两种用法，
`Negation pseudo-class selector (:not())` 能完全兼容 Chrome
而 `Selector list argument` ,也就是这次用的只支持 88 以上的 Chrome

**Comment by CberYellowstone** [comment]
> emmm 其实历史版本中有多处使用了 `:not` 选择器... 好像也没出现过很严重的问题
> 我尝试用其他方法实现（

貌似要把 `:not` 里面的 `pre code` 分开表述?
~~好像就是这样的~~

**Comment by bakaomg** [comment]
> 貌似要把 `:not` 里面的 `pre code` 分开表述?

分开表述的话 好像就没法排除了（
想读取子元素有无 `ol` 发现 `each` 内无法获取（

**Comment by CberYellowstone** [comment]
> > 貌似要把 `:not` 里面的 `pre code` 分开表述？
> 
> 分开表述的话 好像就没法排除了（
> 想读取子元素有无 `ol` 发现 `each` 内无法获取（

以下均为瞎说警告(
~~我不是很懂JavaScript ,可能 大概是这样吧~~

---
![image](https://user-images.githubusercontent.com/37031767/115135178-ef6e3a00-a048-11eb-8939-ba6747e6d395.png)

**Comment by bakaomg** [comment]
试了下 是无效的（因为也不是 JQ 而是 MDUI 的 Mini JQ 库）
还是先在后端处理完再输出，曲线救国吧（

**Comment by bakaomg** [comment]
还有二维码的边距到生产环境就没了，蛮奇怪的

**Comment by CberYellowstone** [comment]
> 还有二维码的边距到生产环境就没了，蛮奇怪的

应该也是某个CSS不兼容没生效?

**Comment by bakaomg** [comment]
> 应该也是某个CSS不兼容没生效?

应该不是，我没有用奇怪的语法
仅压缩后的 CSS 才会，可能是某处的空格之类的被压没了（挠头）

**Comment by CberYellowstone** [comment]
> > 应该也是某个 CSS 不兼容没生效？
> 
> 应该不是，我没有用奇怪的语法
> 仅压缩后的 CSS 才会，可能是某处的空格之类的被压没了（挠头）

奇奇怪怪的bug又增加了(

**Comment by bakaomg** [comment]
@CberYellowstone 已修（

**Comment by CberYellowstone** [comment]
目前在学校，明天中午验证一下（

**Comment by bakaomg** [comment]
> 目前在学校，明天中午验证一下（

可（

**Comment by CberYellowstone** [comment]
已解决，Close。
