### ISSUE TITLE
分类和页面有变动侧栏不会自动更新

### ISSUE THREAD

**Issue by sunnyhenry123** [bakaomg/castle-Typecho-Theme#21]
必须要在功能设置/侧边抽屉/抽屉菜单中作出变动才会更新。

**Comment by CberYellowstone** [comment]
~~旧版应该不维护了吧（~~
你看看这个现象和主题的`缓存功能`有没有关系

**Comment by sunnyhenry123** [comment]
> ~旧版应该不维护了吧（~
> 你看看这个现象和主题的`缓存功能`有没有关系
确实是主题的缓存原因，关闭后同时还解决了域名更换后从前台登录提示HTTP0错误的问题
