### ISSUE TITLE
您好，侧边栏的签名在哪更改

### ISSUE THREAD

**Issue by HuanmengQwQ** [bakaomg/castle-Typecho-Theme#22]

**Comment by bakaomg** [comment]
侧边栏的签名为 Typecho 的站点介绍
具体位置 管理后台 -> `设置` -> `基本` -> `站点描述`
![image](https://user-images.githubusercontent.com/40896676/153776750-8d5fb1de-ee85-40f8-b0c5-018a9812811e.png)

**Comment by HuanmengQwQ** [comment]
好的谢谢
