### ISSUE TITLE
追番界面删除后依然显示

### ISSUE THREAD

**Issue by HuanmengQwQ** [bakaomg/castle-Typecho-Theme#23]
显示404 Not Found.

**Comment by bakaomg** [comment]
可能的情况：
1. 启用了配置文件缓存，导致侧栏列表被缓存（解决方案：在外观设置页面保存一次设置触发刷新机制 / 此问题将在这段时间内修复）
2. 手动添加的侧栏菜单

如有其他情况请提供具体的复现过程或截图

**Comment by HuanmengQwQ** [comment]
能解决下Token 有误，请检查服务器时区是否统一这个问题吗

**Comment by bakaomg** [comment]
> 能解决下Token 有误，请检查服务器时区是否统一这个问题吗

出现这个问题是因为服务器时区不同导致，插件的 README  中有说明解决方法
![image](https://user-images.githubusercontent.com/40896676/161445892-7ca3862d-0ebc-48b2-9c8c-124091dd1a04.png)

**\* 如无法解决请继续在此 issue 下回复 (ง •_•)ง**
