### ISSUE TITLE
Typecho 1.2.0 适配请求

### ISSUE THREAD

**Issue by CberYellowstone** [bakaomg/castle-Typecho-Theme#24]
已知问题：直接无法在主题页显示，已经应用的会页面全白

**Comment by bakaomg** [comment]
已经在适配中了，具体可见此条 [commit](https://github.com/bakaomg/castle-Typecho-Theme/commit/a5c7b6b524a0f793bf087a98ece15fd5fd7cc4fd)
不过发布 Release 可能还需要一小段时间，目前还在修复（改）部分内容，具体修改可见 [0.9.x](https://github.com/bakaomg/castle-Typecho-Theme/tree/0.9.x) 分支的提交记录

**Comment by bakaomg** [comment]
发 [release](https://github.com/bakaomg/castle-Typecho-Theme/releases/tag/0.9.7) 了（
