### ISSUE TITLE
追番页无法正常使用

### ISSUE THREAD

**Issue by CberYellowstone** [bakaomg/castle-Typecho-Theme#25]
![image](https://user-images.githubusercontent.com/37031767/161438544-93cb9a94-a7cd-404b-8ec2-8c8c1cbf83eb.png)

**Comment by bakaomg** [comment]
在咕了在咕了.jpg

<img src="https://user-images.githubusercontent.com/40896676/161446050-f0f90fb9-0c44-4556-8a53-b0decf6ce11b.png" height="100" />

**Comment by bakaomg** [comment]
目前是大概能用了，详细请 [查看此 commit](https://github.com/bakaomg/Castle-Plugin/commit/261cf6e65deaf051afe8e48c3165d562fe6732c1)

* 影响用户体验的修改
