### ISSUE TITLE
侧边栏和代码高亮问题

### ISSUE THREAD

**Issue by matchch** [bakaomg/castle-Typecho-Theme#3]
侧边栏只剩 主页 一个按钮了，归档呀分类呀页面呀包括文章总数什么的，都消失了
```的代码没有高亮，全变成粉色了，看着十分奇怪...

Castle还真没咕咕咕啊
tttttttttql
顺便一提，如果能加上打赏功能就更好了，放三个二维码的那种就好

**Comment by matchch** [comment]
Emmm
忘了Github也支持MD了
代码现在都是粉色的...没有之前的高亮了，看起来有些奇怪

**Comment by bakaomg** [comment]
> 侧边栏只剩主页一个按钮了，补充呀分类呀页面呀包括文章总数什么的，都消失了
> 
> ```
> 
> Castle还真没咕咕咕啊
> tttttttttql
> 顺便一提，如果能加上打赏功能就更好了，放三个二维码的那种就好
> ```

侧栏的话看你设置是空了，重新启用主题就行了，如果不行可将 `Castle/core/libs/settingLibs/menu.json` 里面的 JSON 复制到侧栏菜单的设置后保存即可

**Comment by bakaomg** [comment]
> Emmm
> 忘了Github也支持MD了
> 代码现在都是粉色的...没有之前的高亮了，看起来有些奇怪

emmm 还没有写高亮，因为遇到了些问题...

**Comment by matchch** [comment]
嗯 重新启用主题解决了
代码高亮就拜托啦~~
