### ISSUE TITLE
Links插件高危XSS

### ISSUE THREAD

**Issue by matchch** [bakaomg/castle-Typecho-Theme#6]
这个插件之前就有人做过分析，简单来说就是
1. 添加Links无验权，可不登录添加
2. 添加的Links无过滤，可轻易XSS

利用难度低，几乎无条件
具体分析可见: https://cloud.tencent.com/developer/article/1180747
感谢.

**Comment by matchch** [comment]
作为演示，您的博客放了一个XSS的Alert，并无恶意，请看到后立刻删除

**Comment by bakaomg** [comment]
已修复，请尽快更新）

**Comment by matchch** [comment]
感谢 ohmygattttttttql
