### ISSUE TITLE
问题反馈&建议

### ISSUE THREAD

**Issue by CberYellowstone** [bakaomg/castle-Typecho-Theme#7]
`syntax error, unexpected '}', expecting end of file`
启用后打开任意文章都会显示这个
而使用其他主题没有问题
PHP版本 v7.2.27
Mariadb版本 10.5.1
Typecho版本 最新版
![截图](https://s1.ax1x.com/2020/03/21/8R6y4g.png)
__________________________________________________________
这个主题我非常期待,遇到这种问题实属无奈
希望开发者能早日修复该Bug

**Comment by kengwang** [comment]
能提供详细的报错位置吗?

开启Typecho的Debug模式
在Typecho配置文件config.inc.php中添加下面的代码：
```php
/** 开启Debug模式 */
define("__TYPECHO_DEBUG__",true); 
```
然后提供详细的报错信息以便于定位错误
感谢支持与提交错误!

**Comment by CberYellowstone** [comment]
> 能提供详细的报错位置吗？
> 
> 开启 Typecho 的 Debug 模式
> 在 Typecho 配置文件 config.inc.php 中添加下面的代码：
> 
> ```
> /** 开启Debug模式 */
> define("__TYPECHO_DEBUG__",true); 
> ```
> 
> 然后提供详细的报错信息以便于定位错误
> 感谢支持与提交错误！

`syntax error, unexpected '}', expecting end of file
ParseError: syntax error, unexpected '}', expecting end of file in /var/www/typecho/usr/themes/Castle/post.php:86
Stack trace:
#0 /var/www/typecho/var/Typecho/Router.php(138): Widget_Archive->render()
#1 /var/www/typecho/index.php(23): Typecho_Router::dispatch()
#2 {main}
`

**Comment by bakaomg** [comment]
请将 `/usr/themes/Castle/post.php` 第 75 行的 `<?` 改为 `<?php`

**Comment by CberYellowstone** [comment]
> 请将 `/usr/themes/Castle/post.php` 第 75 行的 `<?` 改为 `<?php`

问题已解决,十分感谢!
***
在此请容许我提出亿些建议:

1. 希望能区分开 站点 favicon 和博主头像,单独设置
![截图1](https://s1.ax1x.com/2020/03/21/8WMMb6.png)
2. 希望能开放顶栏颜色自定义,我个人看来透明颜色未免有些单调
![截图2](https://s1.ax1x.com/2020/03/21/8WMdqP.png)
3. 希望能加入头图功能,具体就如下图,这样感觉能使主页在视觉上更加丰富
![截图3](https://s1.ax1x.com/2020/03/21/8WQiQA.png)
4. 希望加入公告功能,具体在上图也能看到

5. 希望加入 跨设备阅读 功能,就是在顶栏加入一个二维码,样式参考:
![截图4](https://s1.ax1x.com/2020/03/21/8WQBO1.png)
![截图5](https://s1.ax1x.com/2020/03/21/8WQsw6.png)
6. 希望在页脚能加入 一言api ,如下图,

> 提供api地址:https://v1.hitokoto.cn/

![截图6](https://s1.ax1x.com/2020/03/21/8W19KA.png)
7. 首页圆角卡片求一个! 如图
![截图7](https://s1.ax1x.com/2020/03/21/8W11aV.png)
8.最后的提议:在文章页面增加一个快速回顶按钮
***
希望开发者能考虑一下
同时望开放打赏通道以便支持开发者


~~一位爱提需求的人转身离去~~

**Comment by bakaomg** [comment]
@CberYellowstone

1. 站点favicon和博主头像 在开发版已经分开
2. 顶栏颜色设置跟随主题色，因为是全屏背景，所以设置顶栏颜色将会很奇怪（在小屏幕中 文章页面 向下滑动时顶栏会自动着色为主题色）
3. 头图的话，不适合我原本的设计（主要是看起来怪怪的）
4. 公告的话正在打算新增
5. 跨设备阅读二维码以及文章分享功能也正准备写
6. 圆角的话可以有（
7. 页脚一言，感觉没什么必要，不过到时会加入自定义页脚，可以手动加入
8. 打赏的话... 可以去爱发电打赏 https://afdian.net/@ohmyga

**Comment by CberYellowstone** [comment]
@ohmyga233

还有一件事,希望加入 即时搜索 功能

**Comment by bakaomg** [comment]
@CberYellowstone

这个可以有（（

**Comment by CberYellowstone** [comment]
![截图](https://s1.ax1x.com/2020/03/21/8hVgAg.png)
此图中有两处问题
1. 强调色在夜间模式有些瞎眼,应该降低明亮度(MDUI提供了明亮度样式,如下图)
![截图2](https://s1.ax1x.com/2020/03/21/8hZACd.png)
2. 文字超出了底色范围(不知道专用名词是什么),就是图中链接的末端
---
希望能得到回复

**Comment by CberYellowstone** [comment]
@ohmyga233

**Comment by CberYellowstone** [comment]
做了个英文翻译文件,却无法正常应用,你看看要不要用吧
[en-US.zip](https://github.com/ohmyga233/castle-Typecho-Theme/files/4363197/en-US.zip)
@ohmyga233

**Comment by bakaomg** [comment]
> 2\. 文字超出了底色范围(不知道专用名词是什么),就是图中链接的末端

超出容器是因为链接被当成一个单词；
强调色眼瞎... 这个我是倒是没一个个颜色去试，全保持 MDUI 默认强调色（如果可以麻烦说下有哪些颜色眼瞎）

**Comment by ohmyga233** [comment]
> 做了个英文翻译文件,却无法正常应用,你看看要不要用吧
> [en-US.zip](https://github.com/ohmyga233/castle-Typecho-Theme/files/4363197/en-US.zip)
> @ohmyga233



> 做了个英文翻译文件,却无法正常应用,你看看要不要用吧
> [en-US.zip](https://github.com/ohmyga233/castle-Typecho-Theme/files/4363197/en-US.zip)
> @ohmyga233

你这个 JSON 第 137 行多了个半角逗号，而且使用 PHP 的 json_decode 出来的结果为空

**Comment by bakaomg** [comment]
> 做了个英文翻译文件,却无法正常应用,你看看要不要用吧
> [en-US.zip](https://github.com/ohmyga233/castle-Typecho-Theme/files/4363197/en-US.zip)
> @ohmyga233

第 134 行多了个半角逗号

**Comment by CberYellowstone** [comment]
英文翻译我修改了,并且重新进行了翻译润色,,经过语法检查无错误,实际测试已经可用
现把一份最终翻译发出来
[en-US.zip](https://github.com/ohmyga233/castle-Typecho-Theme/files/4364523/en-US.zip)

---
眼瞎配色列表我稍后再奉上

**Comment by CberYellowstone** [comment]
> > 2. 文字超出了底色范围 (不知道专用名词是什么), 就是图中链接的末端
> 
> 超出容器是因为链接被当成一个单词；
> 强调色眼瞎... 这个我是倒是没一个个颜色去试，全保持 MDUI 默认强调色（如果可以麻烦说下有哪些颜色眼瞎）

夜间模式导致眼瞎的强调色有
1. Indigo 靛青
2. Cyan 青色
3. Purple 紫色
4. Deep Purple 深紫色 (这个看不清)
5. Teal 蓝绿色 (调暗点就行)
6. Light Green 亮绿色 (调暗点就行)
7. Lime 酸橙色 (调暗点就行)
8. Yellow 黄色 (调暗点就行)
---
暂时就这么多,一些稍微有点瞎眼而我觉得能接受的我就排除了(就2个)
***
另外想问一下,这个 跟随系统切换默认色 有什么作用
![截图](https://s1.ax1x.com/2020/03/22/85OPTx.png)
貌似不是自动随着时间变化而变化 日间/夜间模式
因为我晚上23点打开时仍旧是白色主题
希望能说明一下(文档写了就不会有这种事了XD)

**Comment by bakaomg** [comment]
@CberYellowstone

了解了，下版本会改。
「 跟随系统切换默认色」是根据系统亮色/暗色设配的（如 Windows 的 颜色
![image](https://user-images.githubusercontent.com/40896676/77246938-0801fa00-6c67-11ea-821f-cfec9410f773.png)
）
文档我也想尽快写完哇，主要是作业太多了，没什么时间去完善（（

**Comment by CberYellowstone** [comment]
@ohmyga233 

既然是这样的话能不能加入 按照时间切换日间/夜间模式的功能
毕竟大晚上的打开的第一眼就瞎了可不太好😂
主要是手机用户

**Comment by ohmyga233** [comment]
> 按照时间切换日间/夜间模式的功能

按照时间的话.. 可以是可以，我研究研究吧

**Comment by bakaomg** [comment]
@CberYellowstone

按照时间的话.. 可以是可以，我研究研究吧

**Comment by CberYellowstone** [comment]
@ohmyga233 

`<?php

date_default_timezone_set("Asia/Shanghai");

$time=date("H");

echo "当前时间:".$time."\n";

if ($time<="6" or $time>="22") {

  echo "夜间模式";

} elseif ($time>="7" && $time<"22") {

  echo "日间模式";
}
?>`
***
这就是一个简单的自动切换实现
由于我技术有限,未能在源码内找到夜间模式的接口
所以希望这段代码能对你有帮助(虽然大佬肯定会)

**Comment by bakaomg** [comment]
@CberYellowstone

我觉得还是用 JS 获取用户的系统时间来实现这个功能体验可能会比较好？

**Comment by CberYellowstone** [comment]
@ohmyga233 
也是可以的,但是会拖慢亿丢丢的访问速度(尤其是像我这种超低配服务器)

**Comment by CberYellowstone** [comment]
@ohmyga233 
***
我又来提bug了,版本:最新开发版,截至2020年3月25日19:57:50

1. 内置表情的酷安表情系列 无法在文章内使用,否则会吞文章内容(暂时没图,复现率97%)
2. 最新开发版的二维码没设置固定宽高比,惨不忍睹
![二维码问题截图](https://s1.ax1x.com/2020/03/25/8v278K.png)
3. 我枯了,BilibiliSessData是啥?
![8v2vVA.png](https://s1.ax1x.com/2020/03/25/8v2vVA.png)
4.刚刚发现目录树没了,不显示了,如图,确定已经开启了目录树选项
![目录树设置](https://s1.ax1x.com/2020/03/25/8vWo6O.png)
![目录树消失截图](https://s1.ax1x.com/2020/03/25/8vWz1f.png)

> 此问题已经发现罪魁祸首
> 当CDN源选择jsdelivr时目录树会消失

---
建议部分:

1. 二维码按钮我认为不该放在此处,应该改为此处(见下图)
![二维码建议截图](https://s1.ax1x.com/2020/03/25/8vRGZ9.png)

原因如下:
> 读者什么时候会选择跨平台看?当然是要离开电脑前的时候随手切换设备
> 读者在离开电脑前的时候为什么要随手切换设备?
> 因为没看完啊! 所以说切换设备的操作多发生在阅读文章途中
> 若是放现在位置的话切换时还得拉回顶部,影响体验
> 也会影响读者的留存率,而放在顶栏就没这种问题
> 因为顶栏是固定的,可以在途中很方便地使用

以上就是我认为需要这样改的原因
希望开发者能考虑一下

2. 二维码可以植入进度同步功能吗?就是利用页面定位锚,和目录树一个道理,这个技术上可以实现
> 这个功能如果真要上线建议做成可选项,在设置里面管理,原因和页面加载速度慢时体验不佳有关

**Comment by kengwang** [comment]
### 如何获取 **SESSDATA**
#### Chrome
1. 打开[bilibili.com](https://bilibili.com)
2. 按下 `F12` 进入`开发者工具`
3. 选择 `Application` 选项卡
4. 在左边列表选择 Storage - Cookies - `https://www.bilibili.com`
5. 在右边找到 `SESSDATA`, 复制里面的Value
![示意图](https://user-images.githubusercontent.com/30862240/75745509-7b90a580-5d52-11ea-9f4b-df370788f518.png)
#### Firefox
Firefox大同小异,只是在第三步时选择 `存储` 选项卡
#### Microsoft Edge
目前 Edge 已经更换为 Chromium 内核,和Chrome操作一样

(复制自另一个项目的PR)

**Comment by CberYellowstone** [comment]
@kengwang 
@ohmyga233 

还有一件事,目录树的按钮颜色不统一
![8vhXSP.png](https://s1.ax1x.com/2020/03/25/8vhXSP.png)

**Comment by kengwang** [comment]
> ### 如何获取 **SESSDATA**
> #### Chrome
> 1. 打开[bilibili.com](https://bilibili.com)
> 2. 按下 `F12` 进入`开发者工具`
> 3. 选择 `Application` 选项卡
> 4. 在左边列表选择 Storage - Cookies - `https://www.bilibili.com`
> 5. 在右边找到 `SESSDATA`, 复制里面的Value
>    ![示意图](https://user-images.githubusercontent.com/30862240/75745509-7b90a580-5d52-11ea-9f4b-df370788f518.png)
> 
> #### Firefox
> Firefox大同小异,只是在第三步时选择 `存储` 选项卡
> 
> #### Microsoft Edge
> 目前 Edge 已经更换为 Chromium 内核,和Chrome操作一样
> 
> (复制自另一个项目的PR)

请注意,此SESSDATA平均**每个月**过期一次,请注意更换!

**Comment by kengwang** [comment]
> 当CDN源选择jsdelivr时目录树会消失
jsdeliver有CDN缓存,可能要一段时间才能反应过来

> 按钮颜色不统一
 颜色不统一应该是 @ohmyga233 大大设计的吧,这样可以区分开两个按钮的功能, 一样的话也没那么好康了(个人审美勿喷......)

**Comment by kengwang** [comment]
> 二维码宽高比问题
请贴一下网址以及复现过程(屏幕宽高)方便调试

**Comment by CberYellowstone** [comment]
> > 二维码宽高比问题
> > 请贴一下网址以及复现过程 (屏幕宽高) 方便调试

完了,我这边突然全都正常了,要不是有截图我都不信之前有问题
> 额,罪魁祸首还是CDN,关闭CDN就能正常显示了
***
二维码白色背景能改个圆角的,这样更md(逃)
***
追番页不能正常显示,已经填好了相关信息
![设置页截图](https://s1.ax1x.com/2020/03/25/8vojhj.png)
显示时一直在转圈圈,如图(动图)
![转圈圈](https://s1.ax1x.com/2020/03/25/8vIaRI.gif)
保证填写信息都是正确的
![哔哩哔哩cookie](https://s1.ax1x.com/2020/03/25/8vTQHO.png)
> 貌似上面没打码,算了不管了

**Comment by kengwang** [comment]
> > > 二维码宽高比问题
> > > 请贴一下网址以及复现过程 (屏幕宽高) 方便调试
> 
> 完了,我这边突然全都正常了,要不是有截图我都不信之前有问题
> 
> > 额,罪魁祸首还是CDN,关闭CDN就能正常显示了
> 
> 二维码白色背景能改个圆角的,这样更md(逃)
> 
> 追番页不能正常显示,已经填好了相关信息
> ![设置页截图](https://camo.githubusercontent.com/a957beea1ee75b53083dfece10dd1a79f9db0464/68747470733a2f2f73312e617831782e636f6d2f323032302f30332f32352f38766f6a686a2e706e67)
> 显示时一直在转圈圈,如图(动图)
> ![转圈圈](https://camo.githubusercontent.com/dad367cd7b3480628ad9d9e9b5853c87a6184e7f/68747470733a2f2f73312e617831782e636f6d2f323032302f30332f32352f3876496152492e676966)
> 保证填写信息都是正确的
> ![哔哩哔哩cookie](https://camo.githubusercontent.com/ac7f329196e71ce78f8e4cafff240f7d9de8b7f9/68747470733a2f2f73312e617831782e636f6d2f323032302f30332f32352f38765451484f2e706e67)
> 
> > 貌似上面没打码,算了不管了

提供下页面,我看看Network

**Comment by CberYellowstone** [comment]
> > > > 二维码宽高比问题
> > > > 请贴一下网址以及复现过程 (屏幕宽高) 方便调试
> > 
> > 
> > 完了，我这边突然全都正常了，要不是有截图我都不信之前有问题
> > > 额，罪魁祸首还是 CDN, 关闭 CDN 就能正常显示了
> > 
> > 
> > 二维码白色背景能改个圆角的，这样更 md (逃)
> > 追番页不能正常显示，已经填好了相关信息
> > ![设置页截图](https://camo.githubusercontent.com/a957beea1ee75b53083dfece10dd1a79f9db0464/68747470733a2f2f73312e617831782e636f6d2f323032302f30332f32352f38766f6a686a2e706e67)
> > 显示时一直在转圈圈，如图 (动图)
> > ![转圈圈](https://camo.githubusercontent.com/dad367cd7b3480628ad9d9e9b5853c87a6184e7f/68747470733a2f2f73312e617831782e636f6d2f323032302f30332f32352f3876496152492e676966)
> > 保证填写信息都是正确的
> > ![哔哩哔哩cookie](https://camo.githubusercontent.com/ac7f329196e71ce78f8e4cafff240f7d9de8b7f9/68747470733a2f2f73312e617831782e636f6d2f323032302f30332f32352f38765451484f2e706e67)
> > > 貌似上面没打码，算了不管了
> 
> 提供下页面，我看看 Network


追番页链接[https://yellowstone.dns.army:488/33.html](url)

**Comment by kengwang** [comment]
![image](https://user-images.githubusercontent.com/30862240/77537447-16efe300-6ed9-11ea-890e-c4e5ca9a246a.png)

问题在这里哦,

**Comment by CberYellowstone** [comment]
> ![image](https://user-images.githubusercontent.com/30862240/77537447-16efe300-6ed9-11ea-890e-c4e5ca9a246a.png)
> 
> 问题在这里哦，

又是该死的CDN,我现在把CDN关了,还是不行,麻烦请再看一次

**Comment by bakaomg** [comment]
> > ![image](https://user-images.githubusercontent.com/30862240/77537447-16efe300-6ed9-11ea-890e-c4e5ca9a246a.png)
> > 问题在这里哦，
> 
> 又是该死的CDN,我现在把CDN关了,还是不行,麻烦请再看一次

用回本地吧.. Jsdelivr非发行版不建议用

**Comment by bakaomg** [comment]
@CberYellowstone

二维码显示不全是因为你用的是 Jsdelivr 源吧.. 用回本地即可
二维码按钮放顶部找个倒是可以
定位的话实现是可以 不是非常难

**Comment by bakaomg** [comment]
@CberYellowstone

目录树按钮统一反而觉得怪怪的
我到时加个颜色选择吧

**Comment by CberYellowstone** [comment]
> > > ### 如何获取 **SESSDATA**
> > > #### Chrome
> > > 
> > > 1. 打开 [bilibili.com](https://bilibili.com)
> > > 2. 按下 `F12` 进入`开发者工具`
> > > 3. 选择 `Application` 选项卡
> > > 4. 在左边列表选择 Storage - Cookies - `https://www.bilibili.com`
> > > 5. 在右边找到 `SESSDATA`, 复制里面的 Value
> > >    ![示意图](https://user-images.githubusercontent.com/30862240/75745509-7b90a580-5d52-11ea-9f4b-df370788f518.png)
> > > 
> > > #### Firefox
> > > Firefox 大同小异，只是在第三步时选择 `存储` 选项卡
> > > #### Microsoft Edge
> > > 目前 Edge 已经更换为 Chromium 内核，和 Chrome 操作一样
> > > (复制自另一个项目的 PR)
> > 
> > 
> > 还有一件事，目录树的按钮颜色不统一
> > ![8vhXSP.png](https://camo.githubusercontent.com/6064f8f32026abe2ef5e50e9a5f29d8515c8efdc/68747470733a2f2f73312e617831782e636f6d2f323032302f30332f32352f3876685853502e706e67)
> 
> 目录树按钮统一反而觉得怪怪的
> 我到时加个颜色选择吧

所以 追番页 无法显示 的问题有办法解决吗?
追番页链接[https://yellowstone.dns.army:488/33.html](url)

**Comment by bakaomg** [comment]
> > > 二维码宽高比问题
> > > 请贴一下网址以及复现过程 (屏幕宽高) 方便调试
> 
> 完了,我这边突然全都正常了,要不是有截图我都不信之前有问题
> 
> > 额,罪魁祸首还是CDN,关闭CDN就能正常显示了
> 
> 二维码白色背景能改个圆角的,这样更md(逃)
> 
> 追番页不能正常显示,已经填好了相关信息
> ![设置页截图](https://camo.githubusercontent.com/a957beea1ee75b53083dfece10dd1a79f9db0464/68747470733a2f2f73312e617831782e636f6d2f323032302f30332f32352f38766f6a686a2e706e67)
> 显示时一直在转圈圈,如图(动图)
> ![转圈圈](https://camo.githubusercontent.com/dad367cd7b3480628ad9d9e9b5853c87a6184e7f/68747470733a2f2f73312e617831782e636f6d2f323032302f30332f32352f3876496152492e676966)
> 保证填写信息都是正确的
> ![哔哩哔哩cookie](https://camo.githubusercontent.com/ac7f329196e71ce78f8e4cafff240f7d9de8b7f9/68747470733a2f2f73312e617831782e636f6d2f323032302f30332f32352f38765451484f2e706e67)
> 
> > 貌似上面没打码,算了不管了

请检查 `/usr/plugins/Castle/` 下有无目录 `cache` 文件夹，没有请确保插件目录可写

**Comment by bakaomg** [comment]
@CberYellowstone

> 所以 追番页 无法显示 的问题有办法解决吗?
> 追番页链接[https://yellowstone.dns.army:488/33.html](url)

API 403了... 你确定升级时有完整替换主题么 特别是 `主题根目录/core/libs/themeConfig.php`

**Comment by CberYellowstone** [comment]
@ohmyga233 

> API 403 了... 你确定升级时有完整替换主题么 特别是 `主题根目录 /core/libs/themeConfig.php`

cache文件夹状态
![8vjyjJ.png](https://s1.ax1x.com/2020/03/25/8vjyjJ.png)
themeConfig.php状态
![8vvfqs.png](https://s1.ax1x.com/2020/03/25/8vvfqs.png)

**Comment by bakaomg** [comment]
@CberYellowstone  [7#issuecomment-603830029](https://github.com/ohmyga233/castle-Typecho-Theme/issues/7#issuecomment-603830029)

请在 `functions.php` 中 打印（`print_r()`）
`Helper::options()->PluginBangumiType` 和 `Helper::options()->PluginBangumiUID`
如果 `PluginBangumiType` 打印结果为 `0` 则说明 `themeConfig.php` 不是最新的

**Comment by bakaomg** [comment]
@CberYellowstone  [7#issuecomment-603830029](https://github.com/ohmyga233/castle-Typecho-Theme/issues/7#issuecomment-603830029)

等等 主题根目录下为什么有缓存文件夹 不应该在插件目录？

**Comment by CberYellowstone** [comment]
@ohmyga233   [7#issuecomment-603832720](https://github.com/ohmyga233/castle-Typecho-Theme/issues/7#issuecomment-603832720)

原谅我的低级失误,
现在我已经把cache建立在正确目录
并且设置用户为apache,权限777
但是问题依旧存在
***
另外请问所谓的打印操作该如何操作?
我对php不太熟悉,是 web访问调用 还是终端 php functions.php 呢?
麻烦大佬指条路

**Comment by kengwang** [comment]
print_r(Helper::options()->PluginBangumiType);

**Comment by bakaomg** [comment]
@CberYellowstone  [7#issuecomment-603837734](https://github.com/ohmyga233/castle-Typecho-Theme/issues/7#issuecomment-603837734)

直接编辑 `functions.php` 找个位置写
`print_r(Helper::options()->PluginBangumiType);`

**Comment by CberYellowstone** [comment]
@ohmyga233 

我傻了,我已经写进去了,接下来又要做什么
已经试过访问该php文件和php执行该文件了
看起来没反应
![8xPpFA.png](https://s1.ax1x.com/2020/03/25/8xPpFA.png)
😂😂😂

**Comment by kengwang** [comment]
随便访问一个页面,用 F12 的 Network 或 查看源代码 看输出的东西
![image](https://user-images.githubusercontent.com/30862240/77542413-1a876800-6ee1-11ea-925b-f0aeacbd1b22.png)
![image](https://user-images.githubusercontent.com/30862240/77542424-1f4c1c00-6ee1-11ea-816c-f2012b1a8386.png)

**Comment by CberYellowstone** [comment]
> 随便访问一个页面，用 F12 的 Network 或 查看源代码 看输出的东西
> ![image](https://user-images.githubusercontent.com/30862240/77542413-1a876800-6ee1-11ea-925b-f0aeacbd1b22.png)
> ![image](https://user-images.githubusercontent.com/30862240/77542424-1f4c1c00-6ee1-11ea-816c-f2012b1a8386.png)

和你这里一样
![8xi39I.png](https://s1.ax1x.com/2020/03/25/8xi39I.png)

**Comment by CberYellowstone** [comment]
看来貌似文件是最新的?
P.S.现在已经把那行注释了

**Comment by bakaomg** [comment]
bgm 目前还没办法用 只有 bilibili 能正常用

**Comment by CberYellowstone** [comment]
> bgm 目前还没办法用 只有 bilibili 能正常用

等等,那个是我选择错了,我填写的是bilibili的,之前手残选错了
但是即使选择bilibili填写好id和data还是不能使用
![8xkZwD.png](https://s1.ax1x.com/2020/03/25/8xkZwD.png)
![8vojhj.png](https://s1.ax1x.com/2020/03/25/8vojhj.png)
![8vTQHO.png](https://s1.ax1x.com/2020/03/25/8vTQHO.png)

**Comment by kengwang** [comment]
我再康康......

**Comment by kengwang** [comment]
![image](https://user-images.githubusercontent.com/30862240/77543778-1ceac180-6ee3-11ea-93fa-192c5b3947b5.png)

**Comment by bakaomg** [comment]
这个是鉴权

**Comment by CberYellowstone** [comment]
我这边也是看到这个403了,具体是什么原因导致的呢?
@kengwang

**Comment by kengwang** [comment]
![image](https://user-images.githubusercontent.com/30862240/77543997-64714d80-6ee3-11ea-8358-2e38c6b91cd4.png)
![image](https://user-images.githubusercontent.com/30862240/77544011-6affc500-6ee3-11ea-8d3f-b6af671ad043.png)

**Comment by CberYellowstone** [comment]
看起来不是我的锅咯?
(逃)

**Comment by kengwang** [comment]
![image](https://user-images.githubusercontent.com/30862240/77544217-b6b26e80-6ee3-11ea-8ef2-686604bbf3ef.png)
这个auth的算法还是问下 @ohmyga233

**Comment by bakaomg** [comment]
我 md5 后的 auth 和你的完全一致，或许判断部分有问题
但是我这边本地测试完全正常来着

**Comment by CberYellowstone** [comment]
原来不是我的锅(逃)
等结果看看是什么原因导致的😂😂

**Comment by kengwang** [comment]
要不直接变量调试法
```php
private function checkAuth($auth, $type, $uid = NULL) {
  $getAuth = (Helper::options()->PluginAPIAuth) ? Helper::options()->PluginAPIAuth : '';

  if ($type == 'bangumi') {
   $token = md5($type.$getAuth.date('Y-m-d H').$uid.$type);
  }else{
   $token = md5($type.$getAuth.date('Y-m-d H').$type);
  }

  if ($token != $auth) {
echo $auth;
echo '<br>Token:';
echo $token;
   //http_response_code(403);
   die();
  }
 }
```

233

**Comment by ohmyga233** [comment]
![image](https://user-images.githubusercontent.com/40896676/77544677-47894a00-6ee4-11ea-9a95-d82bf69689e4.png)
我本地测试完全正常... 太奇怪了

**Comment by CberYellowstone** [comment]
就我这里的环境出现这个问题吗?
@kengwang 你那里有没有这个问题出现?

**Comment by kengwang** [comment]
@CberYellowstone 改下你的代码,看看哪里的问题 位置: plugin的 `Action.php`

**Comment by bakaomg** [comment]
![image](https://user-images.githubusercontent.com/40896676/77544816-83241400-6ee4-11ea-8420-f77a3147ba72.png)
咱这边测试是正常的（迷惑

**Comment by CberYellowstone** [comment]
> @CberYellowstone 改下你的代码，看看哪里的问题 位置: plugin 的 `Action.php`

如何更改,望指明

**Comment by kengwang** [comment]
在`/usr/plugins/Castle/Action.php` 中 第 81 行应该是 之前截图那里
中间的Castle换成你的配套插件目录名
https://github.com/ohmyga233/castle-Typecho-Theme/issues/7#issuecomment-603855651
改成这样

**Comment by CberYellowstone** [comment]
> 在 `/usr/plugins/Castle/Action.php` 中
> 中间的 Castle 换成你的配套插件目录名

😂😂我是说如何修改此文件
三人行,必有小白(我)

**Comment by CberYellowstone** [comment]
> 在 `/usr/plugins/Castle/Action.php` 中
> 中间的 Castle 换成你的配套插件目录名

我明白了,我知道咋改了

**Comment by CberYellowstone** [comment]
@kengwang @ohmyga233 
![8xZdET.png](https://s1.ax1x.com/2020/03/25/8xZdET.png)

**Comment by kengwang** [comment]
> @kengwang @ohmyga233
> ![8xZdET.png](https://camo.githubusercontent.com/9fcfe6edde53523127f30b80743cf65d8e186932/68747470733a2f2f73312e617831782e636f6d2f323032302f30332f32352f38785a6445542e706e67)

噗,他的生成后咋就不一样!!!!! @ohmyga233

**Comment by bakaomg** [comment]
？？我本地测试没这问题啊

**Comment by CberYellowstone** [comment]
???
我的运行环境在这个issue的开头有提到
和这个有关吗?

**Comment by ohmyga233** [comment]
PHP 版本是没问题的 和数据库无关

**Comment by ohmyga233** [comment]
要不给下 QQ 把你 ftp 信息给下 我康康

**Comment by CberYellowstone** [comment]
那可能是什么问题呢?
太奇怪了(超出了我的理解范围)

**Comment by bakaomg** [comment]
我也挺迷惑的

**Comment by CberYellowstone** [comment]
> 要不给下 QQ 把你 ftp 信息给下 我康康

邮件吧?2844829687@qq.com

**Comment by CberYellowstone** [comment]
> 要不给下 QQ 把你 ftp 信息给下 我康康

QQ也行 434974081

**Comment by CatSouta** [comment]
这issue最长了

**Comment by CberYellowstone** [comment]
时隔多日,我又来发bug&建议列表了
---
Bugs:
1. 我想你已经知道了,就是APlayerAtButtom的手机兼容问题,如图
![手机截图](https://s1.ax1x.com/2020/04/05/GBc0IS.png)
2. 为了凑成列表而加的这项
***
提议:
1. 友链页强烈要求站点图标和卡片背景图片分开设置,如图
![友链页](https://s1.ax1x.com/2020/04/05/GBciUU.png)
实在太丑了!!
2.页脚做点小改吧...对于手机的排版不是很友好
***
咕
---

**Comment by CberYellowstone** [comment]
对了,还有表情的cdn化没做 @ohmyga233 ![表情](https://cdn.jsdelivr.net/gh/CberYellowstone/CDN@4-4/Typecho/usr/themes/Castle/static/img/owo/xwx/xwx7.png)

**Comment by bakaomg** [comment]
表情没做知道 咕咕咕

**Comment by Snowflake-Pink** [comment]
这个 issues 也太长了，引用的我要吐了QwQ
不过主题还是非常好的，我现在用的一个 MD 主题很多设计都太反人类了。

**Comment by bakaomg** [comment]
@CberYellowstone  [7#issuecomment-609380582](https://github.com/ohmyga233/castle-Typecho-Theme/issues/7#issuecomment-609380582)

表情问题已经解决了

**Comment by bakaomg** [comment]
@Snowflake-Pink [7#issuecomment-611405975](https://github.com/ohmyga233/castle-Typecho-Theme/issues/7#issuecomment-611405975)

谢谢啦，
还有引用我已经改掉了（（

**Comment by MoeSakura233** [comment]
咱来力!
咱整了个繁体中文语言包（咋就这么闲呢


[Traditional-CN.zip](https://github.com/ohmyga233/castle-Typecho-Theme/files/4542846/Traditional-CN.zip)

**Comment by bakaomg** [comment]
由于此 issue 过长，如果有新问题请重开新的 issue
