### ISSUE TITLE
番剧图片无法加载

### ISSUE THREAD

**Issue by kengwang** [bakaomg/castle-Typecho-Theme#8]
https://github.com/BigCoke233/miracles/issues/33

![image](https://user-images.githubusercontent.com/30862240/77537082-74cffb00-6ed8-11ea-9402-b2bc3a90c8a0.png)

![image](https://user-images.githubusercontent.com/30862240/77537105-7e596300-6ed8-11ea-85e5-3c38a67f13d3.png)

具体可以看这个Issue,因为Castle主题的设置原因,请全部使用非HTTPS方法

如何检查是否正常?

在追番查看页开F12清除缓存并重载,如无403问题即可

**Comment by kengwang** [comment]
诶,没有复现,再调试下试试?

**Comment by kengwang** [comment]
好吧问题仍然存在

**Comment by bakaomg** [comment]
> 好吧问题仍然存在

不对哇 我有加 `<meta name="referrer" content="same-origin">`
而且我这边完全正常
![image](https://user-images.githubusercontent.com/40896676/77539720-c9757500-6edc-11ea-96ea-543e314bc0d6.png)
![image](https://user-images.githubusercontent.com/40896676/77539782-e1e58f80-6edc-11ea-9767-e2a653e6ff2a.png)

**Comment by kengwang** [comment]
![image](https://user-images.githubusercontent.com/30862240/77540636-64bb1a00-6ede-11ea-848c-22cb34ddd1f9.png)

换成FireFox后问题仍然复现

**Comment by bakaomg** [comment]
> ![image](https://user-images.githubusercontent.com/30862240/77540636-64bb1a00-6ede-11ea-848c-22cb34ddd1f9.png)
> 
> 换成FireFox后问题仍然复现

或许Firefox不支持 `<meta name="referrer">` ？
（没用过Firefox

**Comment by kengwang** [comment]
Chrome和FireFox都已经测试过,最初的那个截图来自Chrome,刚才的截图来自FireFox Devloper Edition (这个版本如果有不支持的东西或者兼容性不佳问题会在控制台返回错误)

**Comment by bakaomg** [comment]
> Chrome和FireFox都已经测试过,最初的那个截图来自Chrome,刚才的截图来自FireFox Devloper Edition

太怪了
如果没办法的话只能将图片缓存在本地了..

**Comment by kengwang** [comment]
https://github.com/BigCoke233/miracles/issues/33#issuecomment-601124723

这个是解决方案

具体是在img标签后加上 `referrerpolicy="no-referrer"`

**Comment by bakaomg** [comment]
> [BigCoke233/miracles#33 (comment)](https://github.com/BigCoke233/miracles/issues/33#issuecomment-601124723)
> 
> 这个是解决方案
> 
> 具体是在img标签后加上 `referrerpolicy="no-referrer"`

懂了（

**Comment by bakaomg** [comment]
`referrerpolicy="no-referrer"` 只对 img 生效
`background-image` 该咋办 🤔

**Comment by kengwang** [comment]
不知道呢.
因为 <meta name="referrer"> 只对img等标签生效
见: https://segmentfault.com/q/1010000014383308
对background-img不生效
所以.......也没办法

**Comment by bakaomg** [comment]
行吧 改成 `<img>` 了

**Comment by bakaomg** [comment]
已经修复了（忘记回复
